### PR TITLE
feat: created a avatar component for Sakhi css library

### PR DESCRIPTION
**Pull request by Manju-sree**
Please review avatar component added to sakhi css library

### CODE REVIEW

**Review by Raghav888 — APPROVED** [review]
Looks good.

**Comment by kotalwar-krishna** [comment]
looks nice

**Review by JantuDeb — APPROVED** [review]
I think `avatar-lg` is self explanatory  you can remove size from `avatar-lg-size`. This is a suggestion from my end, you can keep the class name same if you want to.

**Comment by tushartiwari7** [comment]
Code looks fine!
But deploy it for feedback on UI too.

**Pull request merged**
